- hosts: all
  become: true

  tasks:
    - name: ensure repository key is installed
      get_url:
        url: "https://get.docker.com/"
        dest: "/tmp/docker-installation.sh"
        mode: "0744"
      when: "'nginx_servers' in group_names"

    - name: install docker
      shell: "/tmp/docker-installation.sh"
      when: "'nginx_servers' in group_names"

    - name: ensure directory exists
      file: 
        path: "/tmp/conf.d/"
        state: directory
    - name: configure loadbalancer file
      template:
        src: loadbalancer.conf.j2
        dest: /tmp/conf.d/loadbalancer.conf
      when: "'nginx_servers' in group_names"

    - name: run nginx with loadbalancer	   
      shell: docker run --name testnginx -d -p 8080:80 -v /tmp/conf.d:/etc/nginx/conf.d:ro nginx
      become: true
      when: "'nginx_servers' in group_names"
