---
  - name: install apache2 service 
    apt:
      name: "apache2"
      state: present

  - name: replace intro web file
    template:
      src: "{{apache2_html_file}}.j2"
      dest: "{{ apache2_html_folder }}{{ apache2_html_file }}"
