- hosts: all
  become: true
  tasks:
    - name: get var folder size in MB
      get_folder_size:
        path: "/var"
        outputType: "MB"
      register: size
    
    - name: output the size to the user
      debug:
        msg: "{{ size }}"
