---
  - name: get docker installation script
    get_url:
      url: "{{ docker_url }}"
      dest: "{{ docker_install_script_dir }}{{ docker_install_script }}"
      mode: "0744"
    when: "'nginx_servers' in group_names"

  - name: run docker installation script
    shell: "{{ docker_install_script_dir }}{{ docker_install_script }}"
    when: "'nginx_servers' in group_names"

  - name: ensure nginx temp directory exists
    file: 
      path: "{{ nginx_local_dir }}"
      state: directory
    when: "'nginx_servers' in group_names"

  - name: template loadbalancer file
    template:
      src: "{{ nginx_lb_file }}.j2"
      dest: "{{ nginx_local_dir}}{{ nginx_lb_file }}"
    when: "'nginx_servers' in group_names"

  - name: run nginx container with loadbalancer file
    shell: "docker run --name nginx -d -p 8080:80 -v {{ nginx_local_dir }}:{{ nginx_lb_dir }}:ro nginx"
    become: true
    when: "'nginx_servers' in group_names"
